### ISSUE TITLE
Question: Per package user authentication support

### ISSUE THREAD

**Issue by rbdavison** [AvantiPoint/avantipoint.packages#436]
G'Day,

From my reading of the code it appears that this project supports/provides examples of server level user authentication.

Is it possible to have assign access to packages based upon that authentication?

For example:
1. An unauthenticated user may be able to access local copies of packages mirrored from NuGet.org.
2. An authenticated user may be able to access organisation public packages.
3. An authenticated and authorised user may also be able to access organisation restricted packages.

What I'm hoping to set up is a system where packages are listed and become available only based upon a users authentication. If they don't have the required authentication then they have no knowledge of the packages existence.
i.e. Packages are not listed/available for all actions if the user has the required authenticated access.

**Comment by dansiegel** [comment]
Currently you cannot prevent someone from seeing the package, but you can prevent them from downloading it by implementing the `INuGetFeedActionHandler` and providing your own logic to determine whether the user is authorized for the specific package being downloaded.

https://github.com/AvantiPoint/avantipoint.packages/blob/dffc51814ed166e5e5051a86d26d8c5305cecbe6/src/AvantiPoint.Packages.Hosting/INuGetFeedActionHandler.cs#L7

**Comment by rbdavison** [comment]
G'Day Dan,
Thanks for the quick reply, yes I remember seeing that code and not a lot more and it got me wondering how deep this went.

I'll investigate further and look into adding filtering into the searching and associated auth for each packages... Hmmm... I predict a management nightmare ahead...

Cheers,
