### ISSUE TITLE
System.InvalidOperationException: Response Content-Length mismatch in GetSymbols and GetSymbolsWithPrefix

### ISSUE THREAD

**Issue by ntomasn** [AvantiPoint/avantipoint.packages#453]
The endpoints GET api/download/symbols/{file}/{key}/{file2} and GET api/download/symbols/{prefix}/{file}/{key}/{file2} results in InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 12796).

The cause is that the stream used in the extension method AsMemoryStream is not positioned to 0 before return.

Can you change the code as the following? _(the added line "outputStream.Position = 0;" fixes the exception)_

```
public static MemoryStream AsMemoryStream(this Stream original)
{
    var buffer = new byte[16 * 1024];
    var outputStream = new MemoryStream();
    int read;
    while ((read = original.Read(buffer, 0, buffer.Length)) > 0)
    {
        outputStream.Write(buffer, 0, read);
    }
            
    outputStream.Position = 0;

    return outputStream;
}
```

**Comment by dansiegel** [comment]
Thanks for the repot. Would you like to submit a PR?

**Comment by ntomasn** [comment]
Sure I can submit a PR.
